// Dracula theme for Monaco (https://draculatheme.com). Applied via beforeMount.
import type { editor } from "monaco-editor";

export const DRACULA: editor.IStandaloneThemeData = {
  base: "vs-dark",
  inherit: true,
  rules: [
    { token: "", foreground: "f8f8f2", background: "282a36" },
    { token: "comment", foreground: "6272a4" },
    { token: "string", foreground: "f1fa8c" },
    { token: "string.escape", foreground: "ff79c6" },
    { token: "number", foreground: "bd93f9" },
    { token: "keyword", foreground: "ff79c6" },
    { token: "keyword.control", foreground: "ff79c6" },
    { token: "operator", foreground: "ff79c6" },
    { token: "delimiter", foreground: "f8f8f2" },
    { token: "type", foreground: "8be9fd", fontStyle: "italic" },
    { token: "type.identifier", foreground: "8be9fd" },
    { token: "identifier", foreground: "f8f8f2" },
    { token: "function", foreground: "50fa7b" },
    { token: "entity.name.function", foreground: "50fa7b" },
    { token: "variable", foreground: "f8f8f2" },
    { token: "variable.parameter", foreground: "ffb86c", fontStyle: "italic" },
    { token: "constant", foreground: "bd93f9" },
    { token: "macro", foreground: "8be9fd" },
    { token: "namespace", foreground: "8be9fd", fontStyle: "italic" },
    { token: "annotation", foreground: "6272a4" },
  ],
  colors: {
    "editor.background": "#282a36",
    "editor.foreground": "#f8f8f2",
    "editor.lineHighlightBackground": "#343746",
    "editor.selectionBackground": "#44475a",
    "editor.inactiveSelectionBackground": "#44475a80",
    "editorCursor.foreground": "#f8f8f0",
    "editorWhitespace.foreground": "#424450",
    "editorLineNumber.foreground": "#6272a4",
    "editorLineNumber.activeForeground": "#f8f8f2",
    "editorIndentGuide.background": "#3b3d4a",
    "editor.selectionHighlightBackground": "#424450",
    "editorBracketMatch.background": "#44475a",
    "editorBracketMatch.border": "#bd93f9",
    "editorGutter.background": "#282a36",
    "editorWidget.background": "#21222c",
    "scrollbarSlider.background": "#44475a80",
  },
};
